dist: xenial
language: cpp
compiler: clang
addons:
  apt:
    sources:
    - llvm-toolchain-xenial-7
    packages:
    - libc++-7-dev
    - libc++abi-7-dev
    - doxygen
    - graphviz
    update: true
script:
- CXXFLAGS="-stdlib=libc++" cmake .
- cmake --build .
- cmake --build . --target test
- cmake --build . --target package
- doxygen Doxyfile
deploy:
  - provider: script
    skip_cleanup: true
    script:
    - curl -T print_ip-0.0.$TRAVIS_BUILD_NUMBER-Linux.deb -ualexandrbashkirev:$BINTRAY_API_KEY "https://api.bintray.com/content/alexandrbashkirev/otus_cpp/homeworks/$TRAVIS_BUILD_NUMBER/print_ip-0.0.$TRAVIS_BUILD_NUMBER-Linux.deb;deb_distribution=xenial;deb_component=main;deb_architecture=amd64;publish=1"
  
  - provider: pages
    local_dir: doc
    skip_cleanup: true
    github_token: $GITHUB_TOKEN 
    keep_history: true
    on:
      branch: master